apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-server
  template:
    metadata:
      labels:
        app: my-web-server
    spec:
      containers: # ודאי שיש כאן רווח נכון
      - name: my-web-server
        image: 746041018472.dkr.ecr.us-east-1.amazonaws.com/my-node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-server-service
spec:
  type: ClusterIP
  selector:
    app: my-web-server
  ports:
  - port: 80
    targetPort: 8080